#!/usr/bin/python3
import sys
import debug_lib
from agent import TuringAI

def help_message():
    print("USAGE: ./zappy_ai -p port -n name -h machine")
    exit(0)

def check_args(TuringAI):
    for i in range(1, len(sys.argv)):
        if sys.argv[i] == "-p":
            TuringAI.port = int(sys.argv[i + 1])
        elif sys.argv[i] == "-n":
            TuringAI.team_name = sys.argv[i + 1]
            if TuringAI.team_name == "GRAPHIC":
                print("Error: Team name cannot be GRAPHIC.")
                exit(84)
        elif sys.argv[i] == "-h":
            TuringAI.host = sys.argv[i + 1]
        elif sys.argv[i] == "-e":
            TuringAI.children = True
    if (len(sys.argv) < 2) or sys.argv[1] == "-help":
        help_message()
    if sys.argv[1] == "--debug":
        TuringAI.debug = True
        return
    if TuringAI.port is None or TuringAI.team_name == "":
        help_message()

def clear_inventory(ai):
    for i in range(0, 7):
        ai.inventory[i] = 0
    ai.level = 1


def children_here():
    with open("children_here", "w") as f:
        f.write("Children connected\n")

def main():
    ai = TuringAI()
    check_args(ai)
    ai.conn = debug_lib.ServerConnection(ai)
    if ai.debug:
        ai.conn.connect_to_server_debug()
    ai.conn.connect_to_server(ai.team_name)
    ai.ngames = 0
    if ai.children:
        children_here()
    while True:
        ai.train(ai.conn)
        ai.conn.s.close()
        ai.conn = debug_lib.ServerConnection(ai)
        ai.conn.connect_to_server(ai.team_name)
        ai.ngames += 1
        ai.attempt += 1
        clear_inventory(ai)

if __name__ == "__main__":
    main()
