#!/usr/bin/python3
import socket

def handle_client(connection):
    while True:
        buf = connection.recv(1024)
        if not buf:
            break
        print(buf)
        connection.send("ok".encode())
    connection.close()

def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(('127.0.0.1', 4242))
    sock.listen(5)
    print("Server is listening on port 4242")

    while True:
        connection, address = sock.accept()
        print(f"Connection from {address}")
        handle_client(connection)

if __name__ == "__main__":
    main()
